services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: tasmota-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tasmota_db
      POSTGRES_USER: tasmota_user
      POSTGRES_PASSWORD: tasmota_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tasmota-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasmota_user -d tasmota_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Next.js Frontend
  tasmo-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tasmo-admin
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://tasmota_user:tasmota_password@postgres:5432/tasmota_db?schema=public
    networks:
      - tasmota-network
    depends_on:
      postgres:
        condition: service_healthy

  # Database Administration Tool
  adminer:
    image: adminer:latest
    container_name: tasmota-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - tasmota-network
    depends_on:
      - postgres

  # LDAP Server for Development/Testing
  ldap:
    build:
      context: ./docker/ldap
      dockerfile: Dockerfile
    container_name: tasmota-ldap
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
    ports:
      - "389:389"
      - "636:636"
    networks:
      - tasmota-network
    healthcheck:
      test: ["CMD", "ldapsearch", "-x", "-H", "ldap://localhost:389", "-b", "dc=tasmota,dc=local", "-D", "cn=admin,dc=tasmota,dc=local", "-w", "admin", "(objectClass=*)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # LDAP Admin Interface
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: tasmota-phpldapadmin
    restart: unless-stopped
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8081:80"
    networks:
      - tasmota-network
    depends_on:
      - ldap

volumes:
  postgres_data:
  ldap_data:
  ldap_config:

networks:
  tasmota-network:
    driver: bridge 